version: "3.8"
services:
  app:
    container_name: PicScape-API
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - PORT=${PORT}
      - SECRET=${SECRET}
    pull_policy: build
    env_file:
      - stack.env

  mongo:
    command: mongod --quiet --logpath /dev/null 
    image: mongo
    container_name: PicScape-DB
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    env_file:
      - ./.env

volumes:
  mongodb_data: